### ISSUE TITLE
ui: Profile -> Info - $15

### ISSUE THREAD

**Issue by mwatidy** [mylife-plus/SFW-Microorganism-App#15]
[Wireframes](https://www.figma.com/file/QMm6yXvIhIDIcTLM4nfMEY/SFW-Microorganisms-App?node-id=4%3A0)
Screens:
- Profile -> Info

Complete the view to make it look like the wireframe. 
Please pull the branch create-profile-screen 

Profile should include:- 
- Name
- Photo
- XP, Level, Points
- Connect to drive button
- Settings icon
- Notification

**Comment by ProHDkiller** [comment]
Will do, requesting approval

**Comment by mike-gallego** [comment]
I would like this issue. assign it to me.

**Comment by mwatidy** [comment]
Reviewed and resolved
