### ISSUE TITLE
ui: Authentication -> move "forgot Password" - $15 USD 

### ISSUE THREAD

**Issue by mwatidy** [mylife-plus/SFW-Microorganism-App#18]
[Wireframes](https://www.figma.com/file/QMm6yXvIhIDIcTLM4nfMEY/SFW-Microorganisms-App?node-id=4%3A0)
Screens:
- Authentication

Move forgot password to beneath email and password input fields .

**Comment by ProHDkiller** [comment]
Will do, Requesting approval..

**Comment by Glitched15** [comment]
Can do this
