### ISSUE TITLE
ui: Profile -> Uploads -> List of Uploads - $50 

### ISSUE THREAD

**Issue by mwatidy** [mylife-plus/SFW-Microorganism-App#20]
[Wireframes](https://www.figma.com/file/QMm6yXvIhIDIcTLM4nfMEY/SFW-Microorganisms-App?node-id=4%3A0)
Screens:
- Profile -> Uploads

Create screen that shows a list of uploaded images a user has made.
 
----

Bounty upgraded from $30 to $50 -> structure added and Provider for state management

**Comment by mike-gallego** [comment]
I would like permission to do this.

**Comment by MouyouMoos** [comment]
> I would like permission to do this.

permission granted. you have now the issue

**Comment by mwatidy** [comment]
Pull request merged and issue complete

**Comment by MouyouMoos** [comment]
paid 50$ https://stellar.expert/explorer/public/tx/893208fe5860ad623fd6b1dd8a77c68eeffeef640019866e2d589e111e045e48
