### ISSUE TITLE
UI: Profile -> Settings / Profile -> Settings -> all sub-pages - 65$

### ISSUE THREAD

**Issue by mwatidy** [mylife-plus/SFW-Microorganism-App#23]
Figma: https://www.figma.com/file/QMm6yXvIhIDIcTLM4nfMEY/SFW-Microorganisms-App?node-id=4%3A0

Screens:
- Profile -> Settings
- Profile -> Settings -> Donate
- Profile -> Settings -> Profile
- Profile -> Settings -> Security

**Comment by ProHDkiller** [comment]
Requesting approval

**Comment by ProHDkiller** [comment]
Finished and Merged.
