### ISSUE TITLE
ui: Quiz -> Gallery - $50

### ISSUE THREAD

**Issue by mwatidy** [mylife-plus/SFW-Microorganism-App#24]
[Wireframes](https://www.figma.com/file/QMm6yXvIhIDIcTLM4nfMEY/SFW-Microorganisms-App?node-id=4%3A0)
Screens: 
- Quiz -> Gallery
- Quiz -> Gallery -> Sort
- Quiz -> Gallery -> Filter

**Comment by ProHDkiller** [comment]
Will do, Requesting approval..
Also Requesting edit for the Wireframe design as the Filter Widget is drawn outside the app Screen.
![Screenshot from 2021-09-14 18-42-23](https://user-images.githubusercontent.com/8641466/133307352-931530fc-8490-477f-9374-87939c0b7461.png)

**Comment by MouyouMoos** [comment]
> Also Requesting edit for the Wireframe design as the Filter Widget is drawn outside the app Screen.

yes please edit the design as we discussed in discord. Thank you

**Comment by mike-gallego** [comment]
Has this been done? I would like this as well. I want to power through some issues today.

**Comment by ProHDkiller** [comment]
Worked on a previous issue yesterday, I'll do this one today

**Comment by mwatidy** [comment]
> Has this been done? I would like this as well. I want to power through some issues today.

yes this is complete, let's find you another issue

**Comment by mwatidy** [comment]
Merged and reviewed
