### ISSUE TITLE
ui: Profile -> Uploads -> upload file - $60

### ISSUE THREAD

**Issue by mwatidy** [mylife-plus/SFW-Microorganism-App#28]
[Wireframe](https://www.figma.com/file/QMm6yXvIhIDIcTLM4nfMEY/SFW-Microorganisms-App?node-id=716%3A3346) 
Screen: 
- Profile -> Uploads -> 1. Upload Form 
- Profile -> Uploads -> 2. Upload Form

upload new photo with form

**Comment by ProHDkiller** [comment]
Will take

**Comment by ProHDkiller** [comment]
Done. Requesting approval

**Comment by mwatidy** [comment]
pull request merged and issue closed
