### ISSUE TITLE
logic: Back4App Deployment - 135$

### ISSUE THREAD

**Issue by ProHDkiller** [mylife-plus/SFW-Microorganism-App#63]
**Issue Description**
Deploying Back4App Backend.

**Approach**
- Creating Project in Back4App
- Adding parse_server_sdk to the Flutter Project
- Setting up parse SDK and Other Variables for the Project.
- Refactoring the Project File Structure, so the backend services find a suitable place from the beginning.

**Comment by mwatidy** [comment]
Yes please proceed.

**Comment by ProHDkiller** [comment]
Work Done/TBD:
Delete all the Firebase Code.
Reset the authentication functionalities to Back4App.
Reconfiguring Database
Create common methods to be used for backend communication.
Add Devs to the Admin Dashboard.
