### ISSUE TITLE
UI + Logic : Profile -> Profile Uploads -> Upload Form -> Design Image Model - $155

### ISSUE THREAD

**Issue by ProHDkiller** [mylife-plus/SFW-Microorganism-App#64]
![Screenshot from 2021-09-24 08-46-46](https://user-images.githubusercontent.com/8641466/134651289-0d049ce2-9cb5-40b7-94de-42bda200c58f.png)

Design the Image model where users can zoom in/out and draw a box to outline the microOrganisme.
- Detect the Box Offset and place it in a parameter.

**Comment by haythemd** [comment]
90$ Bounty **PAID**
6 Hours Working with Zoom / Scale / Real Measurements and Setting Methods to make it easy for other developers to work with.

**Comment by Idkwhoami42** [comment]
65$ Bounty -- PAID
4-5 hours Working on UI and custom paint for the rectangle, length and width drawing feature
