### ISSUE TITLE
Logic: Create User Model - $50

### ISSUE THREAD

**Issue by ProHDkiller** [mylife-plus/SFW-Microorganism-App#65]
Create User Model and Link it with Provider.

**Comment by mike-gallego** [comment]
Hello, you can assign this to me. Please provide me all variables and functions needed for this user model provider, along with the information contained in User model (name, img, etc).

**Comment by mike-gallego** [comment]
This will roughly take around 5 hours

**Comment by ProHDkiller** [comment]
Johaness Suggested we Collect only Location ( Optional ) Email address, and a nickname. 
Experience, and Tokens count. User should also have a list of Uploads. a list of Votes. 
if there's any changes we can do them later. 
There's always a question of Security and Database schema that haven't been discussed more precisely. So if there's aa change we can do it later. 
If there's a Suggestion please mention in Discord Channel for further discussion.

**Comment by mike-gallego** [comment]
What is experience? Is that a whole class or just a string? Same thing with votes.

**Comment by MouyouMoos** [comment]
> What is experience? Is that a whole class or just a string? Same thing with votes.

XP is like in a game. you earn xp and you level up

**Comment by MouyouMoos** [comment]
paid 50$ to your solana wallet https://explorer.solana.com/tx/XjcGBpeWfD1rpZup78371U9wrAtgt5Z5om5jtqzy8J7WNtv86ACvsEKbRJDJZv7g9F1aNAK5Gyttuz7zKkTNHcD
