### ISSUE TITLE
ui: Authentication - 5h

### ISSUE THREAD

**Issue by mwatidy** [mylife-plus/SFW-Microorganism-App#8]
[Wireframe](https://drive.google.com/file/d/1a_gFOeLnrD9907lD4xzv-vF1aDkN3X6V/view) Page 2

Screens should include:
1- Register 
2- Login 
3- Forgot Password

Users can register through email and password or Google Sign In

**Comment by MouyouMoos** [comment]
ui: Update logo to new one - 0.167h

**Comment by MouyouMoos** [comment]
Move forgot password to beneath email and password input fields . #18
